version: "2"
services:
  web:
    container_name: transaction-collector
    image: transaction-collector
    build: .
    volumes:
      - ./:/transaction-collector
      - /transaction-collector/node_modules
    links:
      - mongo
    env_file:
    - .env
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    expose:
      - 27017
